# Generated by Django 2.1.5 on 2019-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
